'use strict';
const Bank = require('./DataTypes/Bank');
const Lear = require('./DataTypes/Lear');
const Rating = require('./DataTypes/Rating');
const Card = require('./DataTypes/Card');
const CardDeck = require('./DataTypes/CardDeck');
const PlayerCommand = require('./DataTypes/PlayerCommand');
const Player = require('./DataTypes/Player');

const bank = new Bank(1);
console.log(bank);
console.log(Lear);
console.log(Rating);
const card = new Card(Lear.Diamonds, Rating.Ten);
console.log(card);
const deck = new CardDeck();
console.log(deck);
console.log(deck.TopCard());
console.log(deck.Discard());
console.log(deck.GetHand());
console.log(deck.GetFloop());
console.log(PlayerCommand);
const player = new Player('test', 10000, (p) => (console.log(p)));
console.log(player);
player.Refresh();